"""empty message

Revision ID: 04c0899503b8
Revises: 466e9e2da319
Create Date: 2019-08-12 14:52:29.217869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c0899503b8'
down_revision = '466e9e2da319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel', sa.Column('image_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel', 'image_url')
    # ### end Alembic commands ###
