"""add Child_cmt

Revision ID: 1aeb933543b2
Revises: f95d0ac7022c
Create Date: 2019-08-18 15:50:44.359901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aeb933543b2'
down_revision = 'f95d0ac7022c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ccmt',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_title', sa.String(length=50), nullable=True),
    sa.Column('review_content', sa.Text(), nullable=True),
    sa.Column('fcmt_id', sa.Integer(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['fcmt_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ccmt')
    # ### end Alembic commands ###
