"""alter table comment

Revision ID: 1fdf3fa00b98
Revises: 6f11e87ae720
Create Date: 2019-08-17 09:41:17.953810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fdf3fa00b98'
down_revision = '6f11e87ae720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('booking_date', sa.Date(), nullable=True))
    op.add_column('comment', sa.Column('disabled', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('friend', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('recommend_dish', sa.String(length=50), nullable=True))
    op.add_column('comment', sa.Column('review_content', sa.Text(), nullable=True))
    op.add_column('comment', sa.Column('review_title', sa.String(length=50), nullable=True))
    op.add_column('comment', sa.Column('service', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('star1', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('star2', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('star3', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('takeout', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('vegetable', sa.Integer(), nullable=True))
    op.drop_column('comment', 'posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('posts', mysql.VARCHAR(length=1024), nullable=True))
    op.drop_column('comment', 'vegetable')
    op.drop_column('comment', 'takeout')
    op.drop_column('comment', 'star3')
    op.drop_column('comment', 'star2')
    op.drop_column('comment', 'star1')
    op.drop_column('comment', 'service')
    op.drop_column('comment', 'review_title')
    op.drop_column('comment', 'review_content')
    op.drop_column('comment', 'recommend_dish')
    op.drop_column('comment', 'rating')
    op.drop_column('comment', 'friend')
    op.drop_column('comment', 'disabled')
    op.drop_column('comment', 'booking_date')
    # ### end Alembic commands ###
