"""modify column comment 

Revision ID: 21b654470056
Revises: 9ceff7e0923d
Create Date: 2019-08-12 16:13:08.027290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21b654470056'
down_revision = '9ceff7e0923d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel', sa.Column('comment', sa.Text(), nullable=True))
    op.drop_column('hotel', 'comment1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel', sa.Column('comment1', mysql.TEXT(), nullable=True))
    op.drop_column('hotel', 'comment')
    # ### end Alembic commands ###
