"""empty message

Revision ID: 286396dd0094
Revises: dbd84f38ca27
Create Date: 2019-08-25 14:18:54.491317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286396dd0094'
down_revision = 'dbd84f38ca27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ta', sa.Column('open_time', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ta', 'open_time')
    # ### end Alembic commands ###
