"""empty message

Revision ID: 2be5a914be64
Revises: 68bcb8c87252
Create Date: 2019-08-25 16:16:12.009376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2be5a914be64'
down_revision = '68bcb8c87252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ta', sa.Column('comm', sa.Text(), nullable=True))
    op.add_column('ta', sa.Column('info', sa.Text(), nullable=True))
    op.drop_column('ta', 'comment')
    op.drop_column('ta', 'info_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ta', sa.Column('info_url', mysql.VARCHAR(length=512), nullable=True))
    op.add_column('ta', sa.Column('comment', mysql.VARCHAR(length=1024), nullable=True))
    op.drop_column('ta', 'info')
    op.drop_column('ta', 'comm')
    # ### end Alembic commands ###
