"""alter Child_cmt modify table author to user_id

Revision ID: 5e2c7b41ecb4
Revises: 1aeb933543b2
Create Date: 2019-08-18 15:55:57.933719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e2c7b41ecb4'
down_revision = '1aeb933543b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ccmt', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('ccmt_ibfk_1', 'ccmt', type_='foreignkey')
    op.create_foreign_key(None, 'ccmt', 'user', ['user_id'], ['id'])
    op.drop_column('ccmt', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ccmt', sa.Column('author', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ccmt', type_='foreignkey')
    op.create_foreign_key('ccmt_ibfk_1', 'ccmt', 'user', ['author'], ['id'])
    op.drop_column('ccmt', 'user_id')
    # ### end Alembic commands ###
