"""empty message

Revision ID: 60c346862847
Revises: a3b0ffc51332
Create Date: 2019-08-14 14:48:37.925303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60c346862847'
down_revision = 'a3b0ffc51332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('userid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reservation', 'user', ['userid'], ['id'])
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'reservation_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reservation_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('user_ibfk_1', 'user', 'reservation', ['reservation_id'], ['id'])
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.drop_column('reservation', 'userid')
    # ### end Alembic commands ###
