"""empty message

Revision ID: 64b36a1de661
Revises: 5e2c7b41ecb4
Create Date: 2019-08-19 11:48:03.792194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64b36a1de661'
down_revision = '5e2c7b41ecb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_like',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('love', sa.Column('store_id', sa.Integer(), nullable=True))
    op.drop_constraint('love_ibfk_1', 'love', type_='foreignkey')
    op.create_foreign_key(None, 'love', 'ta', ['store_id'], ['id'])
    op.drop_column('love', 'storeid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('love', sa.Column('storeid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'love', type_='foreignkey')
    op.create_foreign_key('love_ibfk_1', 'love', 'ta', ['storeid'], ['id'])
    op.drop_column('love', 'store_id')
    op.drop_table('comment_like')
    # ### end Alembic commands ###
