"""modify table comment alter column table comment

Revision ID: 6f11e87ae720
Revises: 4bc2f75fc76b
Create Date: 2019-08-17 07:36:54.168222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f11e87ae720'
down_revision = '4bc2f75fc76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('posts', sa.String(length=1024), nullable=True))
    op.drop_column('comment', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('comment', 'posts')
    # ### end Alembic commands ###
