"""empty message

Revision ID: 7336551bcb99
Revises: d7271a6d6e71
Create Date: 2019-08-26 11:07:44.860135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7336551bcb99'
down_revision = 'd7271a6d6e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('title_name', sa.String(length=32), nullable=True))
    op.drop_column('reservation', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('title', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('reservation', 'title_name')
    # ### end Alembic commands ###
