"""empty message

Revision ID: 801449037622
Revises: 2be5a914be64
Create Date: 2019-08-25 16:16:43.207578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '801449037622'
down_revision = '2be5a914be64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ta', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('ta', sa.Column('info_url', sa.Text(), nullable=True))
    op.drop_column('ta', 'comm')
    op.drop_column('ta', 'info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ta', sa.Column('info', mysql.TEXT(), nullable=True))
    op.add_column('ta', sa.Column('comm', mysql.TEXT(), nullable=True))
    op.drop_column('ta', 'info_url')
    op.drop_column('ta', 'comment')
    # ### end Alembic commands ###
