"""empty message

Revision ID: 930aba43f439
Revises: 3bde77cf8c88
Create Date: 2019-08-16 19:46:33.059984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '930aba43f439'
down_revision = '3bde77cf8c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('order_id1', sa.String(length=40), nullable=True))
    op.drop_column('reservation', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('reservation', 'order_id1')
    # ### end Alembic commands ###
