"""empty message

Revision ID: 93d9448b6392
Revises: 286396dd0094
Create Date: 2019-08-25 15:23:34.403153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93d9448b6392'
down_revision = '286396dd0094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('comment', sa.Text(), nullable=True))
    op.drop_column('survey', 'opinion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('opinion', mysql.TEXT(), nullable=True))
    op.drop_column('survey', 'comment')
    # ### end Alembic commands ###
