"""empty message

Revision ID: a83cce0f5cb0
Revises: b88e4b909ffa
Create Date: 2019-08-17 18:09:12.539935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a83cce0f5cb0'
down_revision = 'b88e4b909ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('storeid', sa.Integer(), nullable=True))
    op.drop_constraint('like_ibfk_1', 'like', type_='foreignkey')
    op.create_foreign_key(None, 'like', 'ta', ['storeid'], ['id'])
    op.drop_column('like', 'store_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('store_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.create_foreign_key('like_ibfk_1', 'like', 'ta', ['store_id'], ['id'])
    op.drop_column('like', 'storeid')
    # ### end Alembic commands ###
