"""empty message

Revision ID: bb1e45215f13
Revises: 04c0899503b8
Create Date: 2019-08-12 15:53:41.557666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb1e45215f13'
down_revision = '04c0899503b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel', sa.Column('image_url', mysql.VARCHAR(length=512), nullable=True))
    # ### end Alembic commands ###
