"""empty message

Revision ID: d7271a6d6e71
Revises: 801449037622
Create Date: 2019-08-26 11:07:18.656734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7271a6d6e71'
down_revision = '801449037622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('title', sa.String(length=32), nullable=True))
    op.drop_column('reservation', 'title_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('title_name', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('reservation', 'title')
    # ### end Alembic commands ###
