"""empty message

Revision ID: eecc881fb4b7
Revises: 60c346862847
Create Date: 2019-08-16 18:44:01.736081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eecc881fb4b7'
down_revision = '60c346862847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('title_name', sa.String(length=20), nullable=True))
    op.add_column('ta', sa.Column('reservation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ta', 'reservation', ['reservation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ta', type_='foreignkey')
    op.drop_column('ta', 'reservation_id')
    op.drop_column('reservation', 'title_name')
    # ### end Alembic commands ###
